import { Head, Link, router, usePage } from '@inertiajs/react';
import { useState } from 'react';
import AuthenticatedLayout from '../../../layouts/AuthenticatedLayout.tsx';
import type { SharedPageProps, StatementAccount } from '../../../types/index.ts';

interface Props extends SharedPageProps { assets: StatementAccount[]; liabilities: StatementAccount[]; equity: StatementAccount[]; netIncome: number; totalAssets: number; totalLiabilities: number; totalEquity: number; balanced: boolean; filters: { start_date: string; end_date: string }; }
const money = (value: number) => Math.abs(value).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function BalanceSheet() {
    const page = usePage();
    const { assets, liabilities, equity, netIncome, totalAssets, totalLiabilities, totalEquity, balanced, filters } = page.props as any as Props;
    const [loading, setLoading] = useState(false);
    const submit = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); router.get('/accounting/balance-sheet', Object.fromEntries(new FormData(event.currentTarget).entries()), { preserveState: true, replace: true, onFinish: () => setLoading(false) }); };
    const section = (title: string, accounts: StatementAccount[], total: number) => <section className="mt-8"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3 overflow-x-auto border border-[#dce4d9] bg-[#f8faf6]"><table className="w-full min-w-[500px] text-left text-sm"><thead className="border-b border-[#dce4d9] text-xs uppercase tracking-[0.12em] text-[#789083]"><tr><th className="px-5 py-3">Account code</th><th className="px-5 py-3">Account name</th><th className="px-5 py-3 text-right">Balance</th></tr></thead><tbody className="divide-y divide-[#e5ebe4]">{accounts.map((account) => <tr key={account.id}><td className="px-5 py-4 font-mono text-xs">{account.code}</td><td className="px-5 py-4 font-medium">{account.name}</td><td className="px-5 py-4 text-right">{money(account.balance)}</td></tr>)}</tbody><tfoot className="border-t border-[#dce4d9] font-semibold"><tr><td colSpan={2} className="px-5 py-4 text-right">Total {title}</td><td className="px-5 py-4 text-right">{money(total)}</td></tr></tfoot></table>{accounts.length === 0 && <p className="px-5 py-8 text-center text-sm text-[#789083]">No posted {title.toLowerCase()} through this date.</p>}</div></section>;
    return <AuthenticatedLayout><Head title="Balance Sheet" /><div className="mx-auto max-w-5xl"><div className="flex flex-col justify-between gap-5 border-b border-[#dce4d9] pb-7 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#c17d35]">Accounting reports</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Balance Sheet</h1><p className="mt-2 text-sm text-[#617268]">Assets, liabilities, and equity through the selected end date.</p></div><Link href="/accounting/income-statement" className="text-sm font-semibold text-[#386251]">Income Statement</Link></div><form onSubmit={submit} className="mt-8 grid gap-3 border border-[#dce4d9] bg-[#f8faf6] p-4 sm:grid-cols-3"><input type="date" name="start_date" defaultValue={filters.start_date} className="rounded-lg border-[#ccd8cb] bg-white text-sm" /><input type="date" name="end_date" defaultValue={filters.end_date} className="rounded-lg border-[#ccd8cb] bg-white text-sm" /><button type="submit" disabled={loading} className="rounded-lg bg-[#17352d] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{loading ? 'Loading...' : 'Apply date range'}</button></form>{section('Assets', assets, totalAssets)}{section('Liabilities', liabilities, totalLiabilities)}{section('Equity', equity, totalEquity - netIncome)}<div className="mt-6 flex items-center justify-between border border-[#dce4d9] bg-[#f8faf6] p-5"><span className="font-medium">Net Income for period</span><span className="font-semibold">{money(netIncome)}</span></div><div className={`mt-4 flex items-center justify-between border p-5 ${balanced ? 'border-[#9fc19c] bg-[#eef6eb]' : 'border-[#d99c9c] bg-[#fff0f0]'}`}><span className="font-semibold">{balanced ? 'Balance Sheet is balanced' : 'Balance Sheet is unbalanced'}</span><span className="font-semibold">Assets {money(totalAssets)} · L + E {money(totalLiabilities + totalEquity)}</span></div></div></AuthenticatedLayout>;
}