import { Head, router, usePage } from '@inertiajs/react';
import AuthenticatedLayout from '../../../layouts/AuthenticatedLayout.tsx';
import type { SharedPageProps, StatementAccount } from '../../../types/index.ts';

interface Props extends SharedPageProps { assets: StatementAccount[]; liabilities: StatementAccount[]; equity: StatementAccount[]; netIncome: number; totalAssets: number; totalLiabilities: number; totalEquity: number; balanced: boolean; filters: { start_date: string; end_date: string }; }
const money = (value: number) => value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
export default function FinancialPosition() {
    const { props } = usePage(); const data = props as any as Props;
    const apply = (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); router.get('/accounting/financial-position', Object.fromEntries(form.entries())); };
    const section = (title: string, accounts: StatementAccount[], total: number) => <section><h2 className="border-b-2 border-[#c17d35] pb-2 text-xl font-semibold">{title}</h2>{accounts.map((account) => <div key={account.id} className="flex justify-between border-b border-[#e5ebe4] py-3 text-sm"><span>{account.code} · {account.name}</span><span className="font-medium">{money(account.balance)}</span></div>)}<div className="flex justify-between pt-4 font-semibold"><span>Total</span><span>{money(total)}</span></div></section>;
    return <AuthenticatedLayout><Head title="Posisi Keuangan" /><div className="mx-auto max-w-7xl"><div className="border-b border-[#dce4d9] pb-7"><p className="text-sm font-semibold text-[#c17d35]">Laporan akuntansi</p><h1 className="mt-2 text-3xl font-semibold">Laporan Posisi Keuangan</h1></div><form onSubmit={apply} className="mt-6 flex flex-wrap gap-3"><input type="date" name="start_date" defaultValue={data.filters.start_date} className="rounded-lg border-[#ccd8cb]" /><input type="date" name="end_date" defaultValue={data.filters.end_date} className="rounded-lg border-[#ccd8cb]" /><button className="rounded-lg bg-[#17352d] px-4 py-2 text-sm font-semibold text-white">Filter</button></form><div className="mt-8 grid gap-10 md:grid-cols-2">{section('Aset', data.assets, data.totalAssets)}<div>{section('Liabilitas', data.liabilities, data.totalLiabilities)}{section('Ekuitas', data.equity, data.totalEquity - data.netIncome)}<div className="mt-4 flex justify-between border-t-2 border-[#c17d35] pt-4 font-semibold"><span>Laba/(Rugi) Periode</span><span>{money(data.netIncome)}</span></div><div className="mt-4 flex justify-between font-bold"><span>Total Liabilitas + Ekuitas</span><span>{money(data.totalLiabilities + data.totalEquity)}</span></div></div></div><div className={`mt-8 border-l-4 p-4 text-sm font-semibold ${data.balanced ? 'border-green-600 bg-green-50 text-green-800' : 'border-red-600 bg-red-50 text-red-800'}`}>{data.balanced ? 'Seimbang' : 'Tidak seimbang'}</div></div></AuthenticatedLayout>;
}
