import { Head, Link, useForm, usePage } from '@inertiajs/react';
import { useEffect, useState } from 'react';
import AuthenticatedLayout from '../../../layouts/AuthenticatedLayout.tsx';
import type { ChartOfAccount, SharedPageProps } from '../../../types/index.ts';

interface Line { chart_of_account_id: string; description: string; debit: string; credit: string; }
interface Props extends SharedPageProps { accounts: Pick<ChartOfAccount, 'id' | 'code' | 'name'>[]; }
const blankLine = (): Line => ({ chart_of_account_id: '', description: '', debit: '0.00', credit: '0.00' });
const amount = (value: string) => Number(value) || 0;
const money = (value: number) => value.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function JournalEntriesCreate() {
    const page = usePage();
    const { accounts } = page.props as any as Props;
    const { data, setData, post, processing, errors } = useForm({ transaction_date: new Date().toISOString().slice(0, 10), description: '', lines: [blankLine(), blankLine()] });
    const [submitted, setSubmitted] = useState(false);
    const totalDebit = data.lines.reduce((total, line) => total + amount(line.debit), 0);
    const totalCredit = data.lines.reduce((total, line) => total + amount(line.credit), 0);
    const difference = totalDebit - totalCredit;
    const validLines = data.lines.length >= 2 && totalDebit > 0 && totalCredit > 0 && Math.abs(difference) < 0.005 && data.lines.every((line) => amount(line.debit) >= 0 && amount(line.credit) >= 0 && !(amount(line.debit) > 0 && amount(line.credit) > 0));

    useEffect(() => { if (submitted && Object.keys(errors).length > 0) setSubmitted(false); }, [errors, submitted]);
    const updateLine = (index: number, field: keyof Line, value: string) => setData('lines', data.lines.map((line, lineIndex) => lineIndex === index ? { ...line, [field]: value } : line));
    const submit = (event: React.FormEvent) => { event.preventDefault(); setSubmitted(true); if (validLines) post('/accounting/journal-entries'); };

    return <AuthenticatedLayout><Head title="Create Journal Entry" /><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between border-b border-[#dce4d9] pb-7"><div><p className="text-sm font-semibold text-[#c17d35]">Accounting</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Create journal entry</h1><p className="mt-2 text-sm text-[#617268]">Every journal must balance before it can be saved.</p></div><Link href="/accounting/journal-entries" className="text-sm font-semibold text-[#386251]">Back to journals</Link></div>
        <form onSubmit={submit} className="mt-8 space-y-6"><div className="grid gap-5 border border-[#dce4d9] bg-[#f8faf6] p-6 md:grid-cols-2"><label className="text-sm font-medium">Transaction date<input type="date" value={data.transaction_date} onChange={(event) => setData('transaction_date', event.target.value)} className="mt-2 block w-full rounded-lg border-[#ccd8cb] bg-white" /></label><label className="text-sm font-medium">Description<input value={data.description} onChange={(event) => setData('description', event.target.value)} className="mt-2 block w-full rounded-lg border-[#ccd8cb] bg-white" placeholder="What was this entry for?" /></label></div>
            <div className="overflow-x-auto border border-[#dce4d9] bg-[#f8faf6] p-4"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase tracking-[0.12em] text-[#789083]"><tr><th className="px-2 py-3">Account</th><th className="px-2 py-3">Description</th><th className="px-2 py-3">Debit</th><th className="px-2 py-3">Credit</th><th className="px-2 py-3" /></tr></thead><tbody>{data.lines.map((line, index) => <tr key={index}><td className="px-2 py-2"><select value={line.chart_of_account_id} onChange={(event) => updateLine(index, 'chart_of_account_id', event.target.value)} className="w-full rounded-lg border-[#ccd8cb] bg-white"><option value="">Select account</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.code} · {account.name}</option>)}</select></td><td className="px-2 py-2"><input value={line.description} onChange={(event) => updateLine(index, 'description', event.target.value)} className="w-full rounded-lg border-[#ccd8cb] bg-white" /></td><td className="px-2 py-2"><input type="number" min="0" step="0.01" value={line.debit} onChange={(event) => updateLine(index, 'debit', event.target.value)} className="w-full rounded-lg border-[#ccd8cb] bg-white text-right" /></td><td className="px-2 py-2"><input type="number" min="0" step="0.01" value={line.credit} onChange={(event) => updateLine(index, 'credit', event.target.value)} className="w-full rounded-lg border-[#ccd8cb] bg-white text-right" /></td><td className="px-2 py-2"><button type="button" disabled={data.lines.length <= 2} onClick={() => setData('lines', data.lines.filter((_, lineIndex) => lineIndex !== index))} className="text-sm font-semibold text-[#994c4c] disabled:opacity-30">Remove</button></td></tr>)}</tbody></table><button type="button" onClick={() => setData('lines', [...data.lines, blankLine()])} className="mt-4 text-sm font-semibold text-[#386251]">+ Add line</button></div>
            <div className={`flex flex-col justify-between gap-4 border p-5 sm:flex-row sm:items-center ${validLines ? 'border-[#9fc19c] bg-[#eef6eb]' : 'border-[#e7c5a6] bg-[#fff5e8]'}`}><div><p className="font-semibold">{validLines ? 'Journal is balanced' : 'Journal is not balanced'}</p><p className="mt-1 text-sm text-[#617268]">{validLines ? 'Ready to save as draft.' : 'Add debit and credit lines with equal totals.'}</p></div><div className="grid grid-cols-3 gap-5 text-right text-sm"><div><p className="text-xs text-[#789083]">Total debit</p><p className="mt-1 font-semibold">{money(totalDebit)}</p></div><div><p className="text-xs text-[#789083]">Total credit</p><p className="mt-1 font-semibold">{money(totalCredit)}</p></div><div><p className="text-xs text-[#789083]">Difference</p><p className="mt-1 font-semibold">{money(Math.abs(difference))}</p></div></div></div>
            {submitted && !validLines && <p className="text-sm text-[#994c4c]">Please fix the journal lines before saving.</p>}{errors.lines && <p className="text-sm text-[#994c4c]">{errors.lines}</p>}<button type="submit" disabled={processing || !validLines} className="rounded-lg bg-[#17352d] px-5 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">{processing ? 'Saving...' : 'Save Draft'}</button>
        </form></div></AuthenticatedLayout>;
}